# action.yml
name: 'gh-action-spdx-sbom-generator'
description: 'Runs spdx-sbom-generator cli'
branding:
  icon: 'command'
  color: 'red'
inputs:
  command:
    description: 'spdx-sbom-generator command to run'
    required: false
  version:
    description: 'The version of spdx-sbom-generator to use'
    required: false
    default: latest
  arch:
    description: 'Arch to use for spdx-sbom cli'
    required: false
    default: amd64
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
